[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/search"
  to = "/.netlify/functions/search"
  status = 200

[[redirects]]
  from = "/api/ringo"
  to = "/.netlify/functions/ringo"
  status = 200

[[redirects]]
  from = "/api/metals"
  to = "/.netlify/functions/metals"
  status = 200

[[redirects]]
  from = "/api/cars"
  to = "/.netlify/functions/cars"
  status = 200
